### ISSUE TITLE
Elastica dev package required

### ISSUE THREAD

**Issue by Skemeth** [symfony-bundles/fork-bundle#17]
I'm having trouble to install this "fork" package. When I requrie it with compose,r I get the following error message:

"- The requested package friendsofsymfony/elastica-bundle (locked at 5.0.x-dev, required as ^5.0) is satisfiable by friendsofsymfony/elastica-bundle[5.0.x-dev] but these conflict with your requirements or minimum-stability."

Since fork requires only 2 packages, I guess it's in one of the dependencies, but can't figure which one...

**Comment by khaperets** [comment]
I guess, if you change the version for "friendsofsymfony/elastica-bundle" to "^5.0" - it should help

**Comment by Skemeth** [comment]
Sorry I got confused by composer. It was, indeed, a problem on my side.
