### ISSUE TITLE
process fork without the full bundle

### ISSUE THREAD

**Issue by ghost** [symfony-bundles/fork-bundle#2]
Hi,

Many people use the Process Component without using Symfony complete framework, which is my case.
I've had a look at the code, and it seems that it could be quite possible to use the fork feature without using it as a bundle (if I've understood correctly, the bundle part is simple registering the bundle for DI, which is no absolutely necessary for the fork to work.
Is there a way to make it possible to use the features without the bundle part? I've not seen any option in composer to do this (it's possible to update only a root dependency, but only if it's already installed).
One way would be to split the package in two parts... I may fork it and remove the pieces I don't need, but I'm not sure about how to handle the updates you would make and merge them only in the files I would've kept...

Any idea?

**Comment by khaperets** [comment]
Hi!

You can use this functionality as a library, for example:

```
use SymfonyBundles\ForkBundle\Service\Fork;
use SymfonyBundles\ForkBundle\Service\Process;

$fork = new Fork(new Process);

$fork->attach(new FirstTask)->attach(new SecondTask)->run();
```

**Comment by ghost** [comment]
Hi,

Thanks for your answer. I know that: I just don't want to download all the dependencies I don't require and will never ever use... To use it as a lbrary, I have to `composer require symfony-bundles/fork-bundle` which will download many Symfony components I don't want (starting with `symfony/framework-bundle` which will require `asset`, `cache`, `finder`, etc => I don't need them, I won't use them).

**Comment by khaperets** [comment]
Now in composer.json section **require** contains only "php": ">=5.6".
Other dependencies moved to require-dev.
